/* belli bir cironun üzerinde satış yapan mağazaları getirme */

SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
WHERE TOTALPRICE>=40000
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

/* hiçbir şey çıkmadı niye çünkü biz sales tablosundaki totalprıce a bakıyoruz
   tek başına 40000 olan yok benim bir şehrin toplam cirosu 40000 den büyük mü ona bakmam lazım*/ 


SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
WHERE SUM(TOTALPRICE)>=40000
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC
/* bunda da hata veriyor aggregate fonksiyonu where şartı içinde kullanamazsın diyor
   böyle bir şartın varsa bunu having ile kullanabilirsin*/

SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
GROUP BY CITY
HAVING SUM(TOTALPRICE)>=40000
ORDER BY SUM(TOTALPRICE) DESC

/* şimdi çalıştı işte */

SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
GROUP BY CITY
HAVING SUM(TOTALPRICE)<40000
ORDER BY SUM(TOTALPRICE) DESC

SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
WHERE CITY IN ('ANKARA','İSTANBUL','İZMİR','HATAY','AYDIN')
GROUP BY CITY
HAVING SUM(TOTALPRICE)<40000
ORDER BY SUM(TOTALPRICE) DESC

SELECT CITY, SUM(TOTALPRICE)
FROM SALES 
WHERE CITY IN ('ANKARA','İSTANBUL','İZMİR','HATAY','AYDIN')
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC


SELECT CITY, SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES 
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
ORDER BY SUM(TOTALPRICE) DESC


SELECT CITY, SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT
FROM SALES 
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>500
AND SUM(TOTALPRICE)>300000
ORDER BY SUM(TOTALPRICE) DESC