SELECT 
COUNT(A.ID)ADRESSAYISI, COUNT(U.NAMESURNAME)KISIAD, COUNT(DISTINCT U.NAMESURNAME) FARKLIAD,
COUNT(C.ID) ULKESAYISI, COUNT(DISTINCT C.ID) FARKLIULKESAYISI, COUNT(CT.ID) SEHIRSAYISI,
COUNT(DISTINCT CT.ID) FARKLISEHIRSAYISI
FROM
USERS U, ADDRESS A, COUNTRIES C, 
CITIES CT, TOWNS T, DISTRICTS D

WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
	  AND T.ID=A.TOWNID AND D.ID=A.DISTRICTID
AND U.ID=1
AND CT.CITY LIKE 'ANKARA'

GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>=1
/* GROUP BY COUNT DISTINCT gibi fonksiyonları kullanabiliyoruz */

SELECT * FROM USERS

