DECLARE @ISIM AS VARCHAR(100)='ÖMER'
SELECT @ISIM

DECLARE @SAYI1 AS INTEGER
SET @SAYI1=15
DECLARE @SAYI2 AS INTEGER
SET @SAYI2=20

SELECT @SAYI1, @SAYI2

SELECT @SAYI1 AS SAYI1, @SAYI2 AS SAYI2, @SAYI1+@SAYI2 AS TOPLAM

DECLARE @TOPLAM AS INTEGER
SET @TOPLAM= @SAYI1+@SAYI2

SELECT @SAYI1 AS SAYI1, @SAYI2 AS SAYI2,@TOPLAM AS TOPLAM


DECLARE
@SAYI3 AS INTEGER,
@SAYI4 AS INTEGER,
@TOPLAM2 AS INTEGER

SET @SAYI3=5
SET @SAYI4=10
SET @TOPLAM2 = @SAYI3+@SAYI4


SELECT * FROM ISIMLER

DECLARE @ISIM2 AS VARCHAR(100)
DECLARE @TELEFON2 AS VARCHAR(100)

SELECT * FROM ISIMLER WHERE ID=1

SELECT 
@ISIM2 = ISIM, @TELEFON2 = TELEFON
/*ısımler tablosundaki sütun isimlerini verdik*/

FROM ISIMLER WHERE ID=1

SELECT @ISIM2, @TELEFON2

DECLARE @TARIH AS DATETIME
SET @TARIH =GETDATE()
SELECT @TARIH
