SELECT 
ITM.ID, ITM.ITEMCODE URUNKODU, ITM.ITEMNAME URUNADI,
DBO.GET_ITEM_MINPRICE(ITM.ID) AS ENDUSUKFIYAT,
DBO.GET_ITEM_MAXPRICE(ITM.ID) AS ENYUKSEKFIYAT,
DBO.GET_ITEM_AVGPRICE(ITM.ID) AS ORTALAMAFIYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS TOPLAMSATIS,

FROM ITEMS ITM

/*	Aga şimdi de fonksiyon çöplüğü oldu bunların amacı çalışma mantığı benziyor birbirine
	bir tanesi max diğeri min vs çalıştığı tablo aynı mantık aynı bunlar için farklı farklı
	fonksiyonlar oluşturmaya gerek yok 2 yolu var bir tanesi içine değişken gönderirsin
	o değişkene göre çalışır 
*/


CREATE FUNCTION DBO.GET_ITEM_PRICE(@ITEMID AS INT,@PRICETYPE AS VARCHAR(10) )
RETURNS FLOAT
AS
BEGIN
	DECLARE @RESULT AS FLOAT
	IF @PRICETYPE='MIN'
	BEGIN 
		SELECT @RESULT = MIN(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID 
	END

	IF @PRICETYPE='MAX'
	BEGIN 
		SELECT @RESULT = MAX(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID 
	END

	IF @PRICETYPE='AVG'
	BEGIN 
		SELECT @RESULT = AVG(UNITPRICE) FROM ORDERDETAILS OD WHERE OD.ITEMID=@ITEMID 
	END

END

/* artık yukarıdaki işi şöyle yapıcaz */


SELECT 
ITM.ID, ITM.ITEMCODE URUNKODU, ITM.ITEMNAME URUNADI,
DBO.GET_ITEM_PRICE(ITM.ID,'MIN') AS ENDUSUKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'MAX') AS ENYUKSEKFIYAT,
DBO.GET_ITEM_PRICE(ITM.ID,'AVG') AS ORTALAMAFIYAT,
DBO.GET_ITEM_TOTALSALE(ITM.ID) AS TOPLAMSATIS,

FROM ITEMS ITM

/* yine aynı işi yaptı ama bu sefer fonksiyon çöplüğüne dönmedi tek fonk ile hallettik */