
SELECT TOP 10 

U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, U.TELNR1,U.TELNR2,
C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE, A.ADDRESSTEXT ACIKADRES ,
O.ID SIPARISID, ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI, ITM.BRAND MARKA,
ITM.CATEGORY1 KATEGORI1 ,ITM.CATEGORY2 KATEGORI2 ,
ITM.CATEGORY3 KATEGORI3 ,ITM.CATEGORY4 KATEGORI4 ,
OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT, OD.LINETOTAL SATIRTOPLAMI,

CONVERT(DATE,O.DATE_) SIPARISTARIHI, CONVERT(TIME,O.DATE_) SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'

END AS AY,

CASE /* DW= DAY OF WEEK YANİ HAFTANIN GÜNÜ*/
	WHEN DATEPART(DW,O.DATE_)=2  THEN '1.PZT'
	WHEN DATEPART(DW,O.DATE_)=3  THEN '2.SAL'
	WHEN DATEPART(DW,O.DATE_)=4  THEN '3.ÇAR'
	WHEN DATEPART(DW,O.DATE_)=5  THEN '4.PER'
	WHEN DATEPART(DW,O.DATE_)=6  THEN '5.CUM'
	WHEN DATEPART(DW,O.DATE_)=7  THEN '6.CMT'
	WHEN DATEPART(DW,O.DATE_)=1  THEN '7.PZR'
/* neden 1 pazar çünkü abd de haftanın 1.günü pazar sayılıyor
   ayarlardan değiştirirsen ancak o zaman olur
*/
END AS HAFTANINGUNU

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID



CREATE VIEW VW_SIPARIS_DETAYLI
AS

SELECT 
U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, U.TELNR1,U.TELNR2,
C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE, A.ADDRESSTEXT ACIKADRES ,
O.ID SIPARISID, ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI, ITM.BRAND MARKA,
ITM.CATEGORY1 KATEGORI1 ,ITM.CATEGORY2 KATEGORI2 ,
ITM.CATEGORY3 KATEGORI3 ,ITM.CATEGORY4 KATEGORI4 ,
OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT, OD.LINETOTAL SATIRTOPLAMI,

CONVERT(DATE,O.DATE_) SIPARISTARIHI, CONVERT(TIME,O.DATE_) SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'

END AS AY,

CASE /* DW= DAY OF WEEK YANİ HAFTANIN GÜNÜ*/
	WHEN DATEPART(DW,O.DATE_)=2  THEN '1.PZT'
	WHEN DATEPART(DW,O.DATE_)=3  THEN '2.SAL'
	WHEN DATEPART(DW,O.DATE_)=4  THEN '3.ÇAR'
	WHEN DATEPART(DW,O.DATE_)=5  THEN '4.PER'
	WHEN DATEPART(DW,O.DATE_)=6  THEN '5.CUM'
	WHEN DATEPART(DW,O.DATE_)=7  THEN '6.CMT'
	WHEN DATEPART(DW,O.DATE_)=1  THEN '7.PZR'
/* neden 1 pazar çünkü abd de haftanın 1.günü pazar sayılıyor
   ayarlardan değiştirirsen ancak o zaman olur
*/
END AS HAFTANINGUNU

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID



/*  view oluşturduk artık bunun üzerinden istenilen senaryoya göre 
	kendi viewlarımızı oluşturalım
*/

SELECT TOP 10
KATEGORI1, SUM(SATIRTOPLAMI)
FROM  VW_SIPARIS_DETAYLI
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC

/* burda ne yaptık gerçek bir view ı başka bir view içinde kullandık*/ 
CREATE VIEW VW_TOP10_KATEGORI
AS
SELECT TOP 10
KATEGORI1, SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM  VW_SIPARIS_DETAYLI
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP10_KATEGORI /* ÇATIR ÇATIR DA ÇALIŞIYOR */


CREATE VIEW VW_MAGAZA_ANALIZI
AS
SELECT 
SEHIR, SUM(SATIRTOPLAMI) AS TOPLAMTUTAR /* buraya sütun ismi vermezsen view oluşmaz */
FROM VW_SIPARIS_DETAYLI
GROUP BY SEHIR

SELECT TOP 10  * FROM VW_MAGAZA_ANALIZI



CREATE VIEW VW_TOP_10_MUSTERI_LISTESI
AS
SELECT TOP 10
KULLANICIADI, ADSOYAD, SEHIR, ILCE, ACIKADRES, TELNR1, TELNR2, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP_10_MUSTERI_LISTESI


ALTER VIEW VW_TOP_100_MUSTERI_LISTESI
AS
SELECT TOP 100
KULLANICIADI, ADSOYAD, SEHIR, ILCE, ACIKADRES, TELNR1, TELNR2, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2
ORDER BY SUM(SATIRTOPLAMI) DESC

/* komutu çalıştırdığımda top 10 u top 100 olarak güncellicek */

SELECT TOP 100
KULLANICIADI, ADSOYAD, SEHIR, ILCE, ACIKADRES, TELNR1, TELNR2, SUM(SATIRTOPLAMI) TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELNR1,TELNR2
/* GROUP BY OLD. İÇİN HAVING kullanmam lazım değil mi aggregate fonk. old. için */
HAVING SUM(SATIRTOPLAMI)>10000


/* ama eğer bunu view dan çekersek havıng yerine where kullanabiliriz */

SELECT * FROM VW_TOP_100_MUSTERI_LISTESI

WHERE TOPLAMTUTAR>10000

/*  view isterse arka tarafta aggregate fonksiyonlarla çalışmış olsun
	ne yaparsa yapsın o bizim için bir tablo gibi hareket ediyor artık
*/
