SELECT * FROM WORKERS WHERE WORKERBARCODE='EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF'

/*CREATE PROC*/

CREATE PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
/* fonksiyonlardaki gibi değişken oluşturabiliyoruz */
AS
BEGIN
	SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
END 
/*	programmability nin altında store procedure un altında oluştu 
	çağırmak istiyorum nasıl çağırıcam
*/

/* EXEC SP_CARD_CONTROL ama bu çalışmaz çünkü parametre ile çalışıyor ve biz parametreyi vermedik */

EXEC SP_CARD_CONTROL 'EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF' /* ya bu şekilde */
EXEC SP_CARD_CONTROL @WORKERBARCODE='EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF' /* ya da bu */


/* barkodlu kayıt yoksa hata bastırak nasıl yapıcaz bunu */

ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN

	IF EXISTS(SELECT * FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE)
	BEGIN
		SELECT 'KART DOĞRU'
	END
	ELSE
	BEGIN
		SELECT 'KART GEÇERSİZ'
	END
END 



ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	
	SELECT @WORKERNAME =WORKERNAME FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	SELECT @WORKERNAME =WORKERNAME FROM WORKERS WHERE WORKERBARCODE = 'EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF'
	SELECT @WORKERNAME

END 



ALTER PROCEDURE SP_CARD_CONTROL
@WORKERBARCODE AS VARCHAR(50)
AS
BEGIN
	DECLARE @WORKERNAME AS VARCHAR(100)
	
	SELECT @WORKERNAME =WORKERNAME FROM WORKERS WHERE WORKERBARCODE = @WORKERBARCODE
	--SELECT @WORKERNAME =WORKERNAME FROM WORKERS WHERE WORKERBARCODE = 'EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF'
	 
	IF @WORKERNAME IS NULL
	BEGIN
		SELECT 'KART GEÇERSİZ'
		RAISEERROR('KART GEÇERSİZ',16,1) -- bu da mesaj göstermez hata fırlatır
		RETURN -- programı kırar
	END
	ELSE
	BEGIN
		SELECT @WORKERNAME
	END
END 

EXEC SP_CARD_CONTROL @WORKERBARCODE='AB96802C-B13D-484C-BAAC-0AE5E1FEF4EF'