/* stored procedure ler raporlama amacıyla da kullanılır*/
CREATE PROC SP_SATISLAR
@BASTARIH AS DATE,
@BITTARIH AS DATE,
@SEHIR AS VARCHAR(20)
AS
BEGIN


	SELECT 
	U.USERNAME_ KULLANICIADI, U.NAMESURNAME ADSOYAD, U.TELNR1,U.TELNR2,
	C.COUNTRY ULKE, CT.CITY SEHIR, T.TOWN ILCE, A.ADDRESSTEXT ACIKADRES ,
	O.ID SIPARISID, ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI, ITM.BRAND MARKA,
	ITM.CATEGORY1 KATEGORI1 ,ITM.CATEGORY2 KATEGORI2 ,
	ITM.CATEGORY3 KATEGORI3 ,ITM.CATEGORY4 KATEGORI4 ,
	OD.AMOUNT MIKTAR, OD.UNITPRICE BIRIMFIYAT, OD.LINETOTAL SATIRTOPLAMI,

	CONVERT(DATE,O.DATE_) SIPARISTARIHI, CONVERT(TIME,O.DATE_) SIPARISZAMANI,
	DATEPART(YEAR,O.DATE_) YIL,
	DBO.MONTHNAME_(O.DATE_) AS AY,
	DBO.DAYOFWEEK_(O.DATE_) AS HAFTANINGUNU,

	FROM 
	ORDERDETAILS OD
	INNER JOIN ORDERS O ON OD.ORDERID= O.ID
	INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
	INNER JOIN USERS U ON O.USERID = U.ID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

	WHERE O.DATE_ BETWEEN @BASTARIH AND @BITTARIH
	AND CT.CITY LIKE '%'  /* AND CT.CITY LIKE @SEHIR */

END


EXEC SP_SATISLAR '20190101','20190131' /* şehir olmadan önce */
EXEC SP_SATISLAR '20190101','20190131','ANKARA' /* şehir ekledikten sonra */

EXEC SP_SATISLAR '20190101','20190131' 
/* şehire default olarak % verdikten sonra vermezsen bütün şehirleri getirir verirsen verdiğin şehri */