SELECT * FROM ITEMS 


SELECT IOTYPE GCTIPI , SUM(AMOUNT) GCMIKTARI, COUNT(IOTYPE) GCISLEMSAYISI FROM ITEMTRANSACTIONS WHERE ITEMID = 1

GROUP BY IOTYPE


SELECT *,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =1 ) AS GIRIS_SAYISI,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =2 ) AS CIKIS_SAYISI
FROM ITEMS ITM

SELECT *,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =1 ) 
-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =2 ) AS STOKSAYISI
FROM ITEMS ITM


SET STATISTICS IO ON

SELECT *,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =1 ) 
-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =2 ) AS STOKSAYISI
FROM ITEMS ITM


/*	Bu şekilde yaptığımızda 8116 page okudu biz bunun yerine sadece stok sayılarını ayrı bir
	tabloda tutsak ve stok sayılarını ordan çeksek daha iyi olmaz mı e yapalım amk
*/

SELECT ID,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =1 ) 
-
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID = ITM.ID AND IOTYPE =2 ) AS STOKSAYISI
FROM ITEMS ITM
ORDER BY ID

SET STATISTICS IO ON
SELECT * FROM STOCK

/*	sadece 4 page okuyarak olayı hallettik 2000 kat performans kazandık 
	kayıt güncellendiğinde stock u da güncelleyecek kodları yazıcaz
*/
