
SELECT * FROM ITEMS


UPDATE ITEMS SET UNITPRICE = 90 WHERE ID=6
DELETE FROM ITEMS WHERE ID=6
SELECT * FROM ITEMS_LOG


CREATE TRIGGER TRG_ITEMS_DELETE_UPDATE /* ayrı ayrı 2 taneye ne gerek var aq 2 si bir arada işte */
ON ITEMS
AFTER DELETE,UPDATE 

AS
BEGIN

DECLARE @DELETEDCOUNT AS INT
DECLARE @INSERTEDCOUNT AS INT

SELECT @DELETEDCOUNT = COUNT(*) FROM DELETED
SELECT @INSERTEDCOUNT= COUNT(*) FROM INSERTED

DECLARE @LOG_ACTION_TYPE AS VARCHAR(20)

IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT>0 /* 2 sinde de kayıt varsa bu bir update işlemidir çünkü update te 2 sine de kayıt gidiyor*/
	SET @LOG_ACTION_TYPE='UPDATE'

IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT=0/* deleted de kayıt var ınserted de kayıt yoksa delete işlemidir çünkü delete gidiyor inserted e gitmiyor*/
	SET @LOG_ACTION_TYPE='DELETE'

INSERT INTO ITEMS_LOG

( [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 
  [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME] )

SELECT [ID] , [ITEMCODE] , [ITEMNAME] , [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3],[CATEGORY4], [BRAND], 
	   @LOG_ACTION_TYPE, GETDATE(), SUSER_NAME(),PROGRAM_NAME(),HOST_NAME()

FROM DELETED 

END






CREATE TRIGGER TRG_ITEMS_DELETE
ON ITEMS
AFTER DELETE 

AS
BEGIN

INSERT INTO ITEMS_LOG

( [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 
  [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME] )

SELECT [ID] , [ITEMCODE] , [ITEMNAME] , [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3],[CATEGORY4], [BRAND], 
	   'DELETE', GETDATE(), SUSER_NAME(),PROGRAM_NAME(),HOST_NAME()

FROM DELETED 

END

CREATE TRIGGER TRG_ITEMS_UPDATE
ON ITEMS
AFTER UPDATE 

AS
BEGIN

INSERT INTO ITEMS_LOG

( [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 
  [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME] )

SELECT [ID] , [ITEMCODE] , [ITEMNAME] , [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3],[CATEGORY4], [BRAND], 
	   'UPDATE', GETDATE(), SUSER_NAME(),PROGRAM_NAME(),HOST_NAME()

FROM DELETED /* eski değerleri aldırıcaz onun için deleted tan aldırıyoruz*/

END

SELECT SUSER_NAME() /* hangi kullanıcı ile bağlanmışız yani hangi kullanıcı bize onu söyler */

SELECT PROGRAM_NAME() /* kullanıcının bağlandığı program adını getirir*/

SELECT HOST_NAME() /* hangi serverdan hangi makinadan bağlandığını bize söyler */