DELETE FROM ITEMS WHERE ID = 15 

SELECT * FROM ITEMS WHERE ID = 15 

SELECT * FROM ITEMS_LOG WHERE ID = 15

/*  ITEMS tablomdan GERÇEK olarak SİLİNMEDİ HALA DURUYOR  AMA
	kimin yaptığı ne zaman yaptığı hangi bilgisayardan yaptığı bilgisi loglanmaya devam etti
	kimin sildiğini neyi sildiğini ne zaman sildiğini nerden sildiğini vs hepsini görebilirsin
	tablo orijinal haliyle duruyor hiçbir değişme olmadı
*/ 




/* INSTEAD OF TRIGGER I YAZDIK VE NORMALİNİ DİSABLE ETTİK AKTİF DEĞİL YANİ ŞUAN */

USE [ETRADEILERI]
GO
/****** Object:  Trigger [dbo].[TRG_ITEMS_DELETE_UPDATE]    Script Date: 31.10.2023 16:15:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[TRG_ITEMS_DELETE_UPDATE_INSTEADOF]
ON [dbo].[ITEMS]
INSTEAD OF DELETE,UPDATE 

AS
BEGIN

DECLARE @DELETEDCOUNT AS INT
DECLARE @INSERTEDCOUNT AS INT

SELECT @DELETEDCOUNT = COUNT(*) FROM DELETED
SELECT @INSERTEDCOUNT= COUNT(*) FROM INSERTED

DECLARE @LOG_ACTION_TYPE AS VARCHAR(20)

IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT>0
	SET @LOG_ACTION_TYPE='UPDATE'

IF @DELETEDCOUNT >0 AND @INSERTEDCOUNT=0
	SET @LOG_ACTION_TYPE='DELETE'

INSERT INTO ITEMS_LOG

( [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], 
  [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME] )

SELECT [ID] , [ITEMCODE] , [ITEMNAME] , [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3],[CATEGORY4], [BRAND], 
	   @LOG_ACTION_TYPE, GETDATE(), SUSER_NAME(),PROGRAM_NAME(),HOST_NAME()

FROM DELETED 

END


DELETE FROM ITEMS WHERE ID = 15 /* ITEMS tablomdan GERÇEKTEN sildi LOG a da kaydını attı */ 

SELECT * FROM ITEMS WHERE ID = 15

SELECT * FROM ITEMS_LOG WHERE ID = 15