-- AHMET ÖMER'E 1000 TL PARA GÖNDERİYOR


SELECT C.CUSTOMERNAME, A.ACCOUNTNO, A.ACCOUNTNAME, A.CURRENCY, B.BALANCE FROM  ACCOUNTBALANCE B
INNER JOIN ACCOUNTS  A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID



SELECT * FROM CUSTOMERS

SELECT * FROM ACCOUNTS

SELECT * FROM ACCOUNTBALANCE