/*	PERİYODİK BAKIM PLANLARINI GÖRMEK İÇİN MANAGEMENT IN ALTINDA MAİNTENCE PLAN VAR
	MAİTENANCE PLAN WİZARD YANİ BAKIM PLANI SİHİRBAZI DİYE BİR ŞEY VAR ONA TIKLA

	İSİM VER BİRDEN FAZLA GÖREV DE SEÇEBİLİRSİN HEPSİ İÇİN TEK BİR TANE DE SEÇEBİLİRSİN
	CHANGE-> İSİM VER  SCHEDUAL INI SEÇ GÜNDE 4 DEFA 6 SAATTE BİR VS VS OK NEXT

	ŞİMDİİ ASIL ÖNEMLİ KISIM NELER YAPMAK İSTEDİĞİNİ SEÇECEKSİN
	İNDEX DÜZELTME İSTATİSTİK GÜNCELLEME SHRİNK DATABASE FULL,DIFF,TLOG BACKUP 
	TIKLAYIP SEÇİYORSUN SONRA HANGİ DATABASE İÇİN ÖRN YEDEK ALDIN HANGİ DATABASE İN YEDEĞİ ONU SEÇ
	CRM ETRADE VS VS 
	DESTİNATİON NERE ALMAK İSTİYORSUN BUNLARI
	OPTİONS SIKIŞTIR NE ZAMAN EXPİRE OLSUN İSTERSEN ŞİFRELEYEBİLİYORSUN BACKUP ENCRYPTİON NEXT FİNİSH

	MAİNTENANCE PLANS İÇİNDE OLUŞTU AMA BU ARKA PLANDA ÇALIŞAN BİR İŞ DEĞİL Mİ E BUNU JOB LAR YAPIYOR
	ARKA PLANDA KENDİSİ İÇİN BİR JOB OLUŞTURUYOR İÇİNE BAKTIĞINDA YAPTIĞIN ŞEYLERİ GÖREBİLİRSİN

	DİFF İÇİN DE AYNI ŞEYLER

	