/* ürün kategorilerine göre sipariş dağılımı
*/

SELECT 
	ITM.CATEGORY1, ITM.CATEGORY2, ITM.CATEGORY3,
	SUM(OD.LINETOTAL) AS TOPLAM_SATIS_MIKTARI,
	SUM(OD.AMOUNT) AS TOPLAM_SIPARIS_ADEDI,
	COUNT(OD.ID) AS TOPLAM_SATILAN_URUN_SAYISI	,
	SUM(OD.LINETOTAL) / SUM(OD.AMOUNT) AS BIR_SIPARISIN_ORT_FIYATI,
	SUM(OD.LINETOTAL) / COUNT(OD.ID)   AS BIR_URUNUN_ORT_FİYATI

FROM ORDERS O
	INNER JOIN USERS U ON U.ID = O.USERID
	INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID = A.CITYID
	INNER JOIN TOWNS T ON T.ID = A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID = A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID = O.ID
	INNER JOIN INVOICES I ON I.ORDERID = O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID = O.ID
	INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID

WHERE ITM.CATEGORY1='KOZMETIK'	
--WHERE ITM.CATEGORY1='EV'		
GROUP BY ITM.CATEGORY1,ITM.CATEGORY2, ITM.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC



/* yukarıda bizden istenen şartları yerine getirecek şekilde
   tablolar ekledik o tablolardan ihtiyacımız olan alanları çektik
   ve güzel bir sorgu tasarladık
*/
