/* ödeme türüne göre dağılım */

SELECT 
--DISTINCT PAYMENTTYPE AS ODEMETURU,
DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
CASE
	WHEN PAYMENTTYPE=1 THEN 'KREDI_KARTI'
	WHEN PAYMENTTYPE=2 THEN 'HAVALE/EFT'

END AS ODEME_TURU_ACIKLAMA,

SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS

GROUP BY DATEPART(YEAR,DATE_) ,DATEPART(MONTH,DATE_),PAYMENTTYPE
ORDER BY DATEPART(YEAR,DATE_) ,DATEPART(MONTH,DATE_) 
