/* ÜRÜNLERİN FİYAT ANALİZİ EN ÇOK HANGİ AY SATILDI*/
/*SUBQUERY İLE ÇOK DAHA KOLAY YAPILIYOR */

SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,

(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENDUSUK_FIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENYUKSEK_FIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS TOPLAM_ADET,

( 
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
  INNER JOIN ORDERS O ON OD.ORDERID = O.ID
  WHERE OD.ITEMID=ITM.ID
  GROUP BY DATEPART(MONTH,O.DATE_)
  ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY

FROM ITEMS ITM
ORDER BY ITM.ITEMNAME
