
/* boş gelen kayıtlar var sipariş verilmemiş ben onları görmek istiyorum bunu snasıl yapıcam
   başka bir subquery kullanabiliriz
*/

SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,

(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENDUSUK_FIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENYUKSEK_FIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS TOPLAM_ADET,

( 
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
  INNER JOIN ORDERS O ON OD.ORDERID = O.ID
  WHERE OD.ITEMID=ITM.ID
  GROUP BY DATEPART(MONTH,O.DATE_)
  ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY

FROM ITEMS ITM
ORDER BY 3

-----------------------------------------------------------------

SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,

(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENDUSUK_FIYAT,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ENYUKSEK_FIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS ORTALAMA_FIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID = ITM.ID) AS TOPLAM_ADET,

( 
SELECT TOP 1 DATEPART(MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
  INNER JOIN ORDERS O ON OD.ORDERID = O.ID
  WHERE OD.ITEMID=ITM.ID
  GROUP BY DATEPART(MONTH,O.DATE_)
  ORDER BY SUM(AMOUNT) DESC
) AS ENCOKSATILANAY

FROM ITEMS ITM

WHERE ITM.ID NOT IN (SELECT ITEMID FROM ORDERDETAILS) -- order details te olmayanları getir
/*başka bir yol WHERE (SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) IS NULL
 boş olanları getirttirdik
*/
--WHERE ITEMCODE IN ('10740','11396')
ORDER BY 3

/* yerine göre subquery yerine göre join ama aynı işi join le yapabilyorsan join le yap
   hem performans hem okunabilirlik daha iyi olur*/




-- KULLANICININ SON ADRESİNİ BULMA --

SELECT U.*, A.ADDRESSTEXT, A.ID FROM USERS U
INNER JOIN ADDRESS A ON U.ID=A.USERID
WHERE U.ID=1
ORDER BY A.ID DESC

-- EN SON ADRESİNİ ALMAK İSTİYORUZ BUNU YAPMAK İÇİN SUBQUERY DEN BAŞKA ŞANSIMIZ YOK



SELECT U.*,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID = U.ID ORDER BY ID DESC) SONADRES,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID = U.ID ORDER BY ID ) ILKADRES,
(SELECT COUNT ( ADDRESSTEXT) FROM ADDRESS WHERE USERID = U.ID ) ADRESSAYISI

FROM USERS U

