/* tsql string functions yaz microsoft un var devamı */

--SUBSTRING
DECLARE @KELIME AS VARCHAR(100)
SET @KELIME='MERHABA D�NYA'
SELECT SUBSTRING(@KELIME,9,5)

-- lower upper
DECLARE @KELIME2 AS VARCHAR(100)
SET @KELIME='MeHaBA DuNYa'
SELECT LOWER(@KELIME), UPPER(@KELIME)

-- string birleştirme
DECLARE @AD AS VARCHAR(10)='�MER'
DECLARE @SOYAD AS VARCHAR(20)='�OLAKO�LU'
SELECT @AD +' '+@SOYAD

-- right left
DECLARE @KELIME3 AS VARCHAR(100)
SET @KELIME='MERHABA D�NYA'
SELECT LEFT(@KELIME,7), RIGHT(@KELIME,5)

-- LTRIM RTRIM TRIM
DECLARE @KELIME4 AS VARCHAR(100)='MERHABA D�NYA'
SELECT LTRIM(@KELIME4),RTRIM(@KELIME4),TRIM(@KELIME4), LTRIM(RTRIM(@KELIME4))

-- replace
DECLARE @KELIME5 AS VARCHAR(100)='MERHABA D�NYA'
SELECT REPLACE( REPLACE(@KELIME5,'MERHABA','HELLO'), 'D�NYA','WORLD')

-- len
DECLARE @KELIME6 AS VARCHAR(100)='MERHABA D�NYA'
SELECT LEN(@KELIME6)

-- string split
DECLARE @KELIME7 AS VARCHAR(100)='MERHABA D�NYA'
SELECT * FROM string_split(@KELIME7,' ')
