/* tsql date time functions microsoft şeyi vs vs */

-- DATEADD
DECLARE @TARIH AS DATETIME
SET @TARIH='2023-01-01 00:00:00'
DECLARE @TARIH2 AS DATETIME
SET @TARIH2=DATEADD(YEAR,6,@TARIH)
SET @TARIH2=DATEADD(MONTH,6,@TARIH)
SET @TARIH2=DATEADD(DAY,6,@TARIH)
SET @TARIH2=DATEADD(HOUR,6,@TARIH)
SET @TARIH2=DATEADD(MINUTE,6,@TARIH)
SET @TARIH2=DATEADD(SECOND,6,@TARIH)

SELECT @TARIH,@TARIH2

-- DATEDIFF
DECLARE @TARIH3 AS DATETIME
	SET @TARIH3='2023-01-01 00:00:00'
DECLARE @TARIH4 AS DATETIME
	SET @TARIH4='2022-01-01 00:00:00'

SELECT DATEDIFF(YEAR,@TARIH3,@TARIH4)
SELECT DATEDIFF(MONTH,@TARIH3,@TARIH4)
SELECT DATEDIFF(DAY,@TARIH3,@TARIH4)
SELECT DATEDIFF(MINUTE,@TARIH3,@TARIH4)
SELECT DATEDIFF(SECOND,@TARIH3,@TARIH4)
SELECT DATEDIFF(WEEK,@TARIH3,@TARIH4)

-- DATEFROMPARTS
DECLARE @TARIH5 AS DATETIME
SET @TARIH5=DATEFROMPARTS(2020,8,21)
SELECT @TARIH5

-- DATEPART
DECLARE @TARIH6 AS DATETIME
SET @TARIH6='2019-05-09 21:10:32'
SELECT DATEPART(YEAR,@TARIH6)
SELECT DATEPART(MONTH,@TARIH6)
SELECT DATEPART(DAY,@TARIH6)
SELECT DATEPART(MINUTE,@TARIH6)
SELECT DATEPART(SECOND,@TARIH6)
SELECT DATEPART(WEEK,@TARIH6)

SELECT YEAR(@TARIH6)

-- GETDATE()

SELECT GETDATE()
DECLARE @TARIH7 AS DATETIME
SET @TARIH7='2019-05-09 21:10:32'
SELECT DATEDIFF(YEAR,@TARIH7,GETDATE())
