SELECT 

DATEPART(YEAR,O.DATE_) YIL,DATEPART(MONTH,O.DATE_) AY,
SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)


/* excel veri diğer kaynaklar sql server bağlan database i seç özellikler tanım
   sorguyu yapıştır ama güncelleme istediler her seferinde amele gibi
   excel veri diğer kaynaklar bağlan database i seç yeni sorguyu yapıştır
   bir daha değişim istediler yine aynı şeyi yap vs vs çok fazla amelelik
*/

SELECT 

DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'

END AS AY,


SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)




SELECT 

DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCA'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUB'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MAR'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİS'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAY'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZ'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEM'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞU'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİ'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KAS'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARA'

END AS AY,


SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)

/* excel veri diğer kaynaklar sql server bağlan database i seç özellikler tanım
   sorguyu yapıştır ama güncelleme istediler her seferinde amele gibi
   excel veri diğer kaynaklar bağlan database i seç yeni sorguyu yapıştır
   bir daha değişim istediler yine aynı şeyi yap vs vs çok fazla amelelik
*/


/*  onun yerine bir tane view oluştur view üzerinde değişiklik yap 
	sorguyu değiştirdiğin zaman ise 
	excel veri diğer kaynaklar sql server bağlan yeni sorguyu yaz vs uğraşmıyorsun
	onun yerine Alter ile view ı değiştirdikten sonra sadece yenile yapıyorsun
	excel kendisi tablosunu güncelliyor amele gibi uğraşmıyorsun
	AMA order by ı viewlarda kullanamıyorsun onu sorguda ayrıca yazman lazım
	SELECT * FROM VW_AYLARA_GORE_SATISLAR
	ORDER BY YIL,AY bunu gibi yapman lazım
*/


CREATE VIEW VW_AYLARA_GORE_SATISLAR
AS

SELECT 

DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'

END AS AY,


SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)




ALTER VIEW VW_AYLARA_GORE_SATISLAR
AS
SELECT 

DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCA'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ŞUB'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MAR'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'NİS'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'MAY'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'HAZ'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'TEM'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'AĞU'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'EYL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKİ'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KAS'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARA'

END AS AY,


SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)


ALTER VIEW VW_AYLARA_GORE_SATISLAR
AS

SELECT 

DATEPART(YEAR,O.DATE_) YIL,

CASE
	WHEN DATEPART(MONTH,O.DATE_)=1  THEN '01.OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2  THEN '02.ŞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3  THEN '03.MART'
	WHEN DATEPART(MONTH,O.DATE_)=4  THEN '04.NİSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5  THEN '05.MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6  THEN '06.HAZİRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7  THEN '07.TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8  THEN '08.AĞUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9  THEN '09.EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN '10.EKİM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN '11.KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN '12.ARALIK'

END AS AY,


SUM(AMOUNT) TOPLAMMIKTAR, SUM(LINETOTAL) TOPLAMTUTAR,
COUNT(OD.ID) URUNSAYISI, COUNT(DISTINCT O.ID) MUSTERISAYISI

FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID= O.ID
INNER JOIN ITEMS ITM ON OD.ITEMID= ITM.ID
INNER JOIN USERS U ON O.USERID = U.ID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID = O.ID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
