ALTER PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
DECLARE @WORKERNAME AS VARCHAR(50)
DECLARE @WORKERID AS INT
SELECT @WORKERNAME=WORKERNAME,@WORKERID=ID FROM WORKERS
WHERE WORKERBARCODE=@WORKERBARCODE	

IF @WORKERID IS NULL
BEGIN
RAISERROR ('OKUTULAN KART GEÇERSİZDİR',16,1)
RETURN
END

DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO = IOTYPE FROM WORKERTRANSACTIONS
WHERE WORKERID=@WORKERID AND DATE_>= CONVERT(DATE,GETDATE())
ORDER BY DATE_ DESC

IF @LASTIO = @IOTYPE
BEGIN
IF @IOTYPE = 'G'
BEGIN
RAISERROR('ZATEN İÇERİDE GÖZÜKÜYORSUNUZ, GİRİŞ YAPAMAZSINIZ',16,1)
RETURN
END

IF @IOTYPE = 'C'
BEGIN
RAISERROR('ZATEN DIŞARIDA GÖZÜKÜYORSUNUZ, ÇIKIŞ YAPAMAZSINIZ',16,1)
RETURN
END
		
END


INSERT INTO WORKERTRANSACTIONS (WORKERID,DATE_,IOTYPE,GATEID)
VALUES(@WORKERID,@DATE,@IOTYPE,@GATEID)

SELECT @WORKERNAME AS WORKERNAME, @DATE AS DATE_, @IOTYPE AS IOTYPE
END



SELECT * FROM WORKERTRANSACTIONS

EXEC SP_WORKER_INOUT 'AB96802C-B13D-484C-BAAC-0AE5E1FEF4EF','2020-04-12 10:11:05','G',1
EXEC SP_WORKER_INOUT '2020-04-12 10:11:05','AB96802C-B13D-484C-BAAC-0AE5E1FEF4EF','G',1
/* çalışmaz sıra önemli ya da şöyle yapıcan */

EXEC SP_WORKER_INOUT 
@WORKERBARCODE='EB96802C-B13D-484C-BAAC-0AE5E1FEF4EF',
@DATE='2020-04-12 10:11:25',
@IOTYPE='C',
@GATEID=1

SELECT * FROM WORKERS

