/* JOB OLUŞTURUCAZ SQL SERVER AGENT İLE */

INSERT INTO DATES (DATE_) VALUES (GETDATE())

SELECT  * FROM DATES

/*	SQL SERVER AGENT -> JOB -> NEW JOB 
	GENERAL -> AD VER AÇIKLAMA YAZ VS
	STEPS -> ADIM EKLE HANGİ DATABASE TE ÇALIŞSIN HANGİ TİP SORGU ÇALIŞSIN VE SORGUYU YAZ
	SCHEDULES -> NE ZAMAN ÇALIŞACAĞINI SEÇ HAFTALIK AYLIK GÜNLÜK KAÇ SAATTE DAKİKADA SANİYEDE 1
	ÇALIŞSIN VS VS 
*/
