BACKUP DATABASE [BACKUPTEST] TO
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\SSAGFULLBACKUP' 
WITH NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


BACKUP DATABASE [BACKUPTEST] TO
DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\Backup\SSAGEDIFFBACKUP'
WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'BACKUPTEST-Full Database Backup', SKIP, NOREWIND,
NOUNLOAD,  STATS = 10
GO

/* ŞİMDİ JOB OLUŞTURUP BU SCRİPTLERİ JOB LARA VERİCEZ OTOMATİK YEDEK ALICAK ARTIK */

/* ŞUANDA 61 KB LIK DIFF BACKUP VAR BİRAZ KAYIT ATAK */

SELECT * INTO DATES15 FROM DATES

/*	YENİ KAYIT ATTIĞIMIZ İÇİN ARTIK DİFF BACKUP IN BOYUTU 664 KB A ÇIKTI
	HER YENİ DİFF BACKUP ALINDIĞINDA ARTIK 664 KB ARTACAK
*/
